config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resource :session, only: [ :new, :create, :destroy ]
  resource :broadcasts
  resources :rooms, param: :url_token do
    member do
      delete :exit_room
      post :broadcast_create
      patch :change_aspect
      patch :remove_broadcast
    end
    resources :comments do
      get :get_comment, on: :collection
    end
  end
  resources :users do
    member do
      get :edit_icon
      patch :update_icon
      get :friends
      get :followers
    end
    resources :friendships, only: [ :create, :destroy ]
  end
  resource :help
  resources :boards do
    resources :responses, only: [ :index, :create ]
  end
  get 'news' => 'news#index'
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id            :integer          not null, primary key
#  name          :string(255)      not null
#  url_token     :string(255)      not null
#  number        :integer          not null
#  owner_id      :integer          not null
#  private       :boolean          default(FALSE), not null
#  deletable     :boolean          default(FALSE), not null
#  active_number :integer          default(0), not null
#  full          :boolean          default(FALSE), not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Room < ActiveRecord::Base
  has_many :room_users
  has_many :users, :through => :room_users
  has_many :comments
  belongs_to :owner, :class_name => "User"
  has_many :broadcasts

  validates :name, presence: true
  validates :number, presence: true,
    numericality: {
      only_integer: true, greater_than_or_equal_to: 2
    }

  scope :published, -> { where(deletable: false, private: false) }

  after_initialize :set_url_token

  after_save do
    self.room_users.destroy_all if deletable == true
  end

  def enter
    if active_number < number
      increment! :active_number
      if self.active_number == self.number && self.number == self.room_users.count
        self.update(full: true)
      end
    end
  end

  def exit
    if active_number <= number
      decrement! :active_number
      self.update(full: false) unless self.active_number == self.number
    end
  end

  def owner
    User.find(owner_id)
  end

  def owner_name
    owner.nickname
  end

  private

  def set_url_token
    self.url_token = self.url_token.blank? ? generate_url_token : self.url_token
  end

  def generate_url_token
    token = SecureRandom.urlsafe_base64(40)
    self.class.where(url_token: token).blank? ? token : generate_url_token
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authorize_user, except: :index
  before_action :check_room_owner, only: :broadcast_create
  before_action :niconico_login, only: [ :show, :broadcast_create ]

  def index
    @rooms = Room.published
    if current_user && current_user.active_room?
      @rooms = @rooms.where.not(id: current_user.active_room.id)
    end
  end

  def show
    @room = Room.find_by_url_token(params[:url_token])
    if current_user
      current_user.update(room_url_token: @room.url_token)
    end
    if @room.full? && !@room.users.include?(current_user)
      flash[:alert] = "満員です。"
      redirect_to :rooms
    else
      @broadcast = Broadcast.new unless listener?
      if current_user && !@room.users.include?(current_user)
        flash[:notice] = "入室しました。"
        @room.room_users.create(user: current_user)
      end
    end
    @presenter = {
      :comments => @room.comments.last(100).reverse,
      :form => {
        :action => room_comments_path(room_url_token: @room.url_token),
        :csrf_param => request_forgery_protection_token,
        :csrf_token => form_authenticity_token
      }
    }
    if @room.broadcasts.where(live: true).count > 0
      @live = true
      @room.broadcasts.where(live: true).each.with_index(1) do |broadcast, i|
        if broadcast.niconico?
          status = @api.get_player_status(broadcast.get_id)
          if status[:error].present?
            if status[:error] == "full"
              flash.now[:alert] = "満席のため視聴することができません。(ニコニコ生放送)"
            end
            if status[:error] == "require_community_member"
              flash.now[:alert] = "コミュニティ限定のため視聴することができません。(ニコニコ生放送)"
            end
            broadcast.update(live: false)
            break
          end
        end
      end
      broadcast_create
    end
  end

  def new
    if current_user.active_room?
      flash[:alert] = "既にRoomがあります。Roomは一つしか作成できません。"
      redirect_to :rooms
    else
      @room = current_user.rooms.new
    end
  end

  def create
    if current_user.active_room?
      flash[:alert] = "既にRoomがあります。Roomは一つしか作成できません。"
      redirect_to :rooms
    else
      @room = current_user.rooms.new(room_params)
      @room.owner = current_user
      session[:room_url_token] = @room.url_token
      if @room.save
        redirect_to room_path(url_token: @room.url_token)
      else
        flash.now[:alert] = "エラー"
        render action: 'new'
      end
    end
  end

  def destroy
    current_user.active_room.update(deletable: true)
    flash[:notice] = "Roomを削除しました。"
    redirect_to :rooms
  end

  def exit_room
    @room = Room.find_by(url_token: params[:url_token])
    room_user = current_user.room_users.where(room: @room).first
    room_user.destroy!
    @room.exit
    flash[:notice] = "退室しました。"
    redirect_to :rooms
  end

  def broadcast_create
    if @live
      @broadcasts = @room.broadcasts.where(live: true)
    else
      @room = current_user.rooms.find_by(url_token: params[:broadcast][:url_token])
      @broadcast = @room.broadcasts.new(broadcast_params)
      @room.broadcasts.where(live: true).each.with_index(1) do |broadcast, i|
        if broadcast.niconico?
          status = @api.get_player_status(broadcast.get_id)
          if status[:error].present?
            broadcast.update(live: false)
            break
          end
        end
      end
      if @broadcast.save && @broadcast.niconico?
        render json: [ @broadcast, @room, form_authenticity_token, @broadcast.get_community(@api), @broadcast.get_base_time(@api) ]
      elsif @broadcast.save && @broadcast.twitcasting?
        render json: [ @broadcast, @room, form_authenticity_token, @broadcast.get_userid, @broadcast.get_duration ]
      else
        render json: [ false ]
      end
    end
  end

  def change_aspect
    aspect_ratio = params[:aspect_ratio].split("x")
    width, height = aspect_ratio[0], aspect_ratio[1]
    render json: [ width, height ]
  end

  def remove_broadcast
    broadcast = Broadcast.find(params[:id])
    if broadcast.update(live: false)
      if broadcast.niconico?
        flash[:notice] = "#{broadcast.get_id}を取り消しました。"
      else broadcast.twitcasting?
        flash[:notice] = "#{broadcast.get_userid}のライブを取り消しました。"
      end
    else
      flash.now[:alert] = "エラー"
    end
    redirect_to :back
  end

  private
  def room_params
    params.require(:room).permit(
      :name, :private, :number
    )
  end

  def authorize_user
    unless current_user
      flash[:alert] = "ユーザーログインが必要です。登録していない方は登録してください。"
      redirect_to :rooms
    end
  end

  def broadcast_params
    params.require(:broadcast).permit(:url)
  end

  def check_room_owner
    @room = Room.find_by(url_token: params[:broadcast][:url_token])
    unless current_user.owner?(@room)
      flash[:alert] = "Roomのオーナーではありません。"
      redirect_to :rooms
    end
  end

  def listener?
    current_user.owner?(@room) ? false : true
  end
  helper_method :listener?

  def niconico_login
    @niconico = Niconico.new(ENV['email'], ENV['password']) unless @niconico
    @niconico.login unless @niconico.logined
    @api = Niconico::Live::API.new(@niconico.agent) unless @api
  end
end

app/views/rooms/_broadcast_form.html.erb
<div class="prepareblock">
  <div class="prepareFormField">

    <div style="color:white">
      URLを入力する前に各サイトにログインしてください。
    </div>

    <div style="color:white;">
      <p>
        ニコニコ生放送 例) http://live.nicovideo.jp/watch/lv*******?ref=community
      </p>
      <p>
        TwitCasting 例) http://twitcasting.tv/*******
      </p>
    </div>

    <%= form_for @broadcast, url: [ :broadcast_create, @room ], method: :post, remote: true, html: { class: "pure-form" } do |f| %>
      <%= f.text_field :url, class: "pure-input-1",
        placeholder: "URLを入力 例)http://live.nicovideo.jp/watch/lv*******?ref=community" %>
      <%= f.hidden_field :url_token, value: @room.url_token %>
      <%= f.submit '入力', type: 'submit', class: 'pure-button pure-button-primary' %>
    <% end %>

  </div>
</div>

app/views/rooms/index.html.erb
<h1>Roomとは</h1>
Roomに入ることで他の人とライブストリーミングを共有できます。<br>
Roomを作成、入室したい場合は<%= link_to "無料ユーザー登録・ログイン", :new_user, class: "BaseLink" %>が必要です。
<br>
<br>
<% if current_user && current_user.active_room? %>
  <%= link_to "Roomへ戻る", room_path(url_token: current_user.active_room.url_token), class: 'pure-button' %>
<% else %>
  <%= link_to "Roomを作成する", :new_room, class: 'pure-button' %>
<% end %>

<br>
<br>
<br>
<table class="pure-table pure-table-striped">
  <% if @rooms.present? %>
    <thead>
      <tr>
        <th>
          Room名
        </th>
        <th>
          入室人数 / 人数制限
        </th>
        <th></th>
      </tr>
    </thead>
      <% @rooms.each do |room| %>
        <tr>
          <td>
            <%= room.name %>
          </td>
          <td>
            <%= "#{room.active_number} / #{room.number}" %>
          </td>
          <td>
            <% if room.full? %>
              <div style="color:red;">満員</div>
            <% else %>
              <% unless current_user && current_user.active_room? %>
                <%= link_to 'このRoomへ行く', room_path(url_token: room.url_token) %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
  <% end %>
</table>

app/views/rooms/new.html.erb
<%= form_for @room, html: { class: 'pure-form pure-form-stacked', role: 'form' } do |f| %>
  <%= f.label :name, "Room名" %>
  <%= f.text_field :name, placeholder: "Room名", required: true  %>
  <%= f.label :number, "人数(2人以上)" %>
  <%= f.number_field :number, placeholder: "人数", required: true %>
  <label for="room_private" class="pure-checkbox">
    <%= f.check_box :private %> 鍵部屋
  </label>
  ※鍵部屋にチェックを入れるとRoom一覧から非表示にできます。
  共有したい方へはRoom名か、URLを教えてください。
  <br>
  <%= f.submit "作成", type: 'submit', class: 'pure-button pure-button-primary' %>
<% end %>

app/views/rooms/show.html.erb
<div class="broadcastsField box">
  <% if listener? || @live %>
    <% if @broadcasts.present? %>
      <% @broadcasts.each do |broadcast| %>
        <iframe width="960px" height="488px" frameborder='0' src="<%= broadcast.player_url %>" id="<%= broadcast.id %>">
          <embed type="application/x&#45;shockwave&#45;flash" src="<%= broadcast.player_url %>" name="plugin" height="100%" width="100%"></embed>
        </iframe>
      <% end %>
      <% if @broadcasts.size < 2 && !listener? %>
        <%= render 'broadcast_form' %>
      <% end %>
    <% end %>
  <% else %>
    <%= render 'broadcast_form' %>
  <% end %>
</div>

<div class="sidebar right CommentField">
  <div id="RoomInfoTrigger">▽ </div>
  <div class="RoomInfoField" id="RoomInfoField">
    <b><%= @room.name %></b>
    <small>
      :
      <%= "制限人数 #{@room.active_number}/#{@room.number}人" %>
      <%= "オーナー #{@room.owner_name}" %>
    </small>
    <br>
    <%= image_tag("/images/user_icons/user#{@room.owner.icon_number}.png", size: "35x35") %>

    <div class="BroadcastInfoBlock">
      <% if @live %>
        <% @broadcasts.each do |broadcast| %>
          <div class="CommunityThumbnail">
            <% if broadcast.niconico? %>
              <%= link_to image_tag(Broadcast::URL[:community_thumbnail] + broadcast.get_community(@api)), Broadcast::URL[:community]+broadcast.get_community(@api), :target => "_blank" %>
            <% elsif broadcast.twitcasting? %>
              <%= link_to image_tag(broadcast.get_user_icon), Broadcast::URL[:twitcasting_tv]+broadcast.get_userid, :target => "_blank" %>
            <% end %>
            <% if current_user.owner?(@room) %>
              <%= button_to "取り消し", remove_broadcast_room_path(url_token: @room.url_token), { class: 'RemoveButton InInfoField', id: "#{broadcast.id}", method: :patch, params: { id: "#{broadcast.id}" } } %>
            <% end %>
            <% if broadcast.niconico? %>
              <%= broadcast.get_base_time(@api) %>
            <% elsif broadcast.twitcasting? %>
              <%= broadcast.get_duration %>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <% if current_user.owner?(@room) %>
      <%= button_to 'Roomを削除する', @room, method: :delete, data: { confirm: "この処理は元に戻せません。\n本当に削除しますか？" }, class: 'pure-button InInfoField' %>
    <% else %>
      <%= button_to "退室", exit_room_room_path(url_token: @room.url_token), method: :delete, data: { confirm: "退室しますか？" }, class: 'pure-button InInfoField' %>
    <% end %>

    <br>
    <% if @room.room_users.present? %>
      <% @room.room_users.each do |room_user| %>
        <%= link_to image_tag("/images/user_icons/user#{room_user.user.icon_number}.png", size: "30x30"), user_path(id: room_user.user.id), class: "InInfoField UserLinkImage", title: room_user.user.nickname %>
      <% end %>
    <% end %>

    <%= form_tag change_aspect_room_path(url_token: @room.url_token), { method: :patch, class: 'pure-form', id: "change_aspect_form", remote: true } do %>
      <%= select_tag(:aspect_ratio, options_for_select(["960x488", "840x427", "720x366", "600x305", "480x244", "450x229", "432x220", "360x183", "240x122"]), class: 'InInfoField') %>
    <% end %>
  </div>
  <%= react_component('CommentBox', {:presenter => @presenter.to_json, :pollInterval => 2000}) %>
</div>